runtime: go
api_version: go1

skip_files:
  - ^(.*/)?\.md$
  - ^(.*/)?\.sh$

# Defaults to automatic scaling with these settings:
#
#automatic_scaling:
#  min_num_instances: 2
#  max_num_instances: 20

handlers:
- url: /.*
  script: _go_app
